{
  awk: 'awk -f -'
  bash: 'bash'
  clojure: 'clojure -'
  dot: 'dot -Tpng | display #q'
  html: 'python -m webbrowser #f #q'
  javascript: 'node'
  lua: 'lua'
  makefile: 'make -f -'
  markdown: 'markdown #b:html'
  moonscript: 'moon /dev/stdin'
  pascal: 'instantfpc #f'
  perl: 'perl'
  php: 'php'
  python: 'python'
  ruby: 'ruby'
  -- rust: 'cargo run'
  scss: 'sass -'
}
